### ISSUE TITLE
(1) php-doofinder incompatibilities due to GuzzleHttp

### ISSUE THREAD

**Issue by carlosescri** [doofinder/doofinder-woocommerce#52]
```
2021-02-12T09:26:01+00:00 CRITICAL Uncaught TypeError: Argument 1 passed 
to GuzzleHttp\Client::send() must be an instance of GuzzleHttp\Message\RequestInterface, 
instance of GuzzleHttp\Psr7\Request given, called in 
/path/to/user/root/html/wp-content/plugins/doofinder-for-woocommerce/lib/src/Management/PhpClient/Api/SearchEnginesApi.php on line 1424 
and defined in /path/to/user/root/html/wp-content/plugins/constant-contact-forms/vendor/guzzlehttp/guzzle/src/Client.php:158 

Stack trace: 
#0 /path/to/user/root/html/wp-content/plugins/doofinder-for-woocommerce/lib/src/Management/PhpClient/Api/SearchEnginesApi.php(1424): GuzzleHttp\Client->send(Object(GuzzleHttp\Psr7\Request), Array)
#1 /path/to/user/root/html/wp-content/plugins/doofinder-for-woocommerce/lib/src/Management/PhpClient/Api/SearchEnginesApi.php(1401): DoofinderManagement\Api\SearchEnginesApi->searchEngineShowWithHttpInfo('8bad in /path/to/user/root/html/wp-content/plugins/constant-contact-forms/vendor/guzzlehttp/guzzle/src/Client.php on line 158
```

**Comment by carlosescri** [comment]
"Constant Contact Forms" plugin uses Guzzle: https://plugins.svn.wordpress.org/constant-contact-forms/trunk/vendor/guzzlehttp/
